// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtibosxboseykltulzsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0aWJvc3hib3NleWtsdHVsenNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTMzODgsImV4cCI6MjA1Nzk4OTM4OH0.GqY7JXRaaVpgesNDm1AUZr8pHB3NNYPFQP5GgrQNIAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);